spring:
  cloud:
    function:
      definition: producer
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        mail-topic-out-0:
          destination: mail-topic-event
