server:
  port: 8080
  servlet:
    context-path: /parking

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=parking
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog-master.yaml
  cloud:
    function:
      definition: producer
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        mail-topic-out-0:
          destination: mail-topic-event

